# Generated by Django 3.1.6 on 2021-06-15 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familyinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familyname1', models.CharField(default='', max_length=50)),
                ('familyname2', models.CharField(default='', max_length=50)),
                ('familyname3', models.CharField(default='', max_length=50)),
                ('occupation1', models.CharField(default='', max_length=50)),
                ('occupation2', models.CharField(default='', max_length=50)),
                ('occupation3', models.CharField(default='', max_length=50)),
                ('salary1', models.IntegerField(default='')),
                ('salary2', models.IntegerField(default='')),
                ('salary3', models.IntegerField(default='')),
                ('total_salary', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Inquries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('comments', models.TextField(default='')),
                ('rate', models.CharField(choices=[('2', 'weak'), ('3', 'good'), ('1', 'poor'), ('4', 'very good'), ('5', 'excellent')], default='', max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Psrsignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=50, null=True)),
                ('lastname', models.CharField(default='', max_length=50, null=True)),
                ('address', models.TextField(default='')),
                ('occupation_head', models.CharField(default='', max_length=50)),
                ('salary_head', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='PSRStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(choices=[('DENIED', 'denied'), ('RECEIVED', 'received'), ('PENDING', 'pending')], default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subsidyconfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('contact', models.IntegerField(default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('subsidy', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Receivingplacedate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[('Phase 1', 'PHASE1'), ('Phase 2', 'PHASE2'), ('Phase 3', 'PHASE3'), ('Phase 4', 'PHASE 4')], default='', max_length=50, null=True)),
                ('date', models.DateField(default='')),
                ('time', models.TimeField(default='')),
                ('p_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='prac.psrsignup')),
            ],
        ),
        migrations.CreateModel(
            name='Receivingbankpawnshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_pawnshop', models.CharField(choices=[('Landbank', 'LANDBANK'), ('PNB', 'PNB'), ('MLHUILLER', 'MLHUILLER'), ('PALAWAN', 'PALAWAN')], default='', max_length=50, null=True)),
                ('date', models.DateField(default='')),
                ('time', models.TimeField(default='')),
                ('b_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='prac.psrsignup')),
            ],
        ),
        migrations.CreateModel(
            name='Additionalassistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_address', models.CharField(default='', max_length=50, null=True)),
                ('contact', models.IntegerField(default='')),
                ('loan', models.IntegerField(default='')),
                ('a_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='prac.psrsignup')),
            ],
        ),
    ]
