# Generated by Django 3.1.6 on 2021-05-19 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agegroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agerange', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='pendingname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(default='', max_length=50, null=True)),
                ('l_name', models.TextField(default='')),
                ('phase', models.CharField(choices=[('Phase 1', 'Phase 1'), ('Phase 2', 'Phase 2'), ('Phase 3', 'Phase 3'), ('Phase 4', 'Phase 4')], default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subsidy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_member', models.IntegerField(default='')),
                ('file2', models.FileField(blank=True, null=True, upload_to='')),
                ('id_members', models.ImageField(blank=True, null=True, upload_to='')),
                ('subsidy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation_head', models.CharField(default='', max_length=50)),
                ('salary_head', models.IntegerField(default='')),
                ('id_head', models.ImageField(blank=True, null=True, upload_to='')),
                ('file1', models.FileField(blank=True, null=True, upload_to='')),
                ('pname', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='prac.pendingname')),
            ],
        ),
        migrations.CreateModel(
            name='FamilySalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member1', models.CharField(default='', max_length=50)),
                ('member2', models.CharField(default='', max_length=50)),
                ('member3', models.CharField(default='', max_length=50)),
                ('occupation1', models.CharField(default='', max_length=50)),
                ('occupation2', models.CharField(default='', max_length=50)),
                ('occupation3', models.CharField(default='', max_length=50)),
                ('salary1', models.IntegerField(default='')),
                ('salary2', models.IntegerField(default='')),
                ('salary3', models.IntegerField(default='')),
                ('total_salary', models.IntegerField(default=None)),
                ('age_range', models.ManyToManyField(to='prac.Agegroup')),
            ],
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_address', models.TextField(default='')),
                ('contact', models.IntegerField(default='')),
                ('applicant_number', models.IntegerField(default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pname', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='prac.pendingname')),
            ],
        ),
    ]
