# Generated by Django 3.1.6 on 2021-05-26 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familyinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familyfirstname', models.CharField(default='', max_length=50, null=True)),
                ('familylastname', models.TextField(default='')),
                ('occupation', models.CharField(default='', max_length=50)),
                ('salary_head', models.IntegerField(default='')),
                ('salary', models.IntegerField(default='')),
                ('total_salary', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Psrlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Psrsignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=50, null=True)),
                ('lastname', models.TextField(default='')),
                ('occupation_head', models.CharField(default='', max_length=50)),
                ('username', models.CharField(default='', max_length=15, null=True)),
                ('password', models.CharField(default='', max_length=15, null=True)),
                ('phase', models.CharField(choices=[('P1', 'Phase 1'), ('P2', 'Phase 2'), ('P3', 'Phase 3'), ('P4', 'Phase 4')], default='', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receivingbank_pawnshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_pawnshop', models.CharField(choices=[('BDO', 'BDO'), ('PNB', 'PNB'), ('MLHUILLER', 'MLHUILLER'), ('PALAWAN', 'PALAWAN')], default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receivingplace_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[('PTM', 'PTM'), ('Metanoiah', 'Metanoiah'), ('Holy', 'Holy'), ('Court', 'Court')], default='', max_length=50, null=True)),
                ('date', models.DateField(default='')),
                ('time', models.TimeField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Subsidyconfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('full_address', models.TextField(default='')),
                ('contact', models.IntegerField(default='')),
                ('applicant_number', models.IntegerField(default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('family_member', models.IntegerField(default='')),
                ('subsidy', models.IntegerField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='confirmation',
            name='pname',
        ),
        migrations.RemoveField(
            model_name='familysalary',
            name='age_range',
        ),
        migrations.RemoveField(
            model_name='item',
            name='pname',
        ),
        migrations.DeleteModel(
            name='Subsidy',
        ),
        migrations.DeleteModel(
            name='Agegroup',
        ),
        migrations.DeleteModel(
            name='Confirmation',
        ),
        migrations.DeleteModel(
            name='FamilySalary',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='pendingname',
        ),
        migrations.AddField(
            model_name='psrlogin',
            name='login',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='prac.psrsignup'),
        ),
        migrations.AddField(
            model_name='familyinfo',
            name='login',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='prac.psrsignup'),
        ),
    ]
