# Generated by Django 3.1.6 on 2021-05-31 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prac', '0002_auto_20210526_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receivingbankpawnshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_pawnshop', models.CharField(choices=[('BDO', 'BDO'), ('PNB', 'PNB'), ('MLHUILLER', 'MLHUILLER'), ('PALAWAN', 'PALAWAN')], default='', max_length=50, null=True)),
                ('date', models.DateField(default='')),
                ('time', models.TimeField(default='')),
            ],
        ),
        migrations.RenameModel(
            old_name='Receivingplace_date',
            new_name='Receivingplacedate',
        ),
        migrations.DeleteModel(
            name='Receivingbank_pawnshop',
        ),
    ]
