# Generated by Django 3.1.6 on 2021-06-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prac', '0003_auto_20210531_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psrsignup',
            name='phase',
        ),
        migrations.AddField(
            model_name='psrsignup',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='psrsignup',
            name='lastname',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
